name: Run Tests and Lint

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Change this to your requirements file

    - name: Run unit tests
      run: python manage.py test todo_app.tests.TodoModelTest

    - name: Run integration tests
      run: python manage.py test todo_app.tests.TodoAPITest

  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Change this to your requirements file

    - name: Run flake8
      run: flake8

    - name: Run black
      run: black --check .  # Use black to check code formatting without modifying files
